server:
  port: 8888
  
spring:
  application:
    name: ms-admin-config-server

#Configuracion Local
  profiles:
    active: native
  cloud:
    config:
      server: 
        native:
          searchLocations: file:///C:/AmbDesarrollo/AMS-CORE_TRIBUTARIO/ms-administracion-data-config  