server:
   port: 9999
   
# SQL -Server #
spring:
  jpa: 
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true
  datasource: 
    url: jdbc:sqlserver://172.22.16.34;trustServerCertificate=true;databaseName=MDMQ_CORE_TRIBUTARIO
    username: GestionMunicipalCoreTributarioUsuario
    password: Gestion%desa
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver


