version: '3'
services:
  ### MySQL database for Clientes
  db-clientes:
    container_name: db-clientes
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_ms_clientes
      MYSQL_USER: userdev
      MYSQL_PASSWORD: Test@123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3308:3306
    expose:
      - 3306

  ### Posgres database for Productos
  db-productos:
    container_name: db-productos
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_ms_productos
      MYSQL_USER: userdev
      MYSQL_PASSWORD: Test@123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3309:3306
    expose:
      - 3306
  
  db-pedidos:
    container_name: db-pedidos
    image: gvenzl/oracle-xe:latest
    restart: unless-stopped
    environment:
      ORACLE_PASSWORD: oracle
      APP_USER: userdev
      APP_USER_PASSWORD: Test@123
    ports:
      - 1521:1521
    expose:
      - 1521