spring:
  application:
    name: ms-negocio-gestion-clientes

  config:
    import: optional:configserver:http://localhost:8888


#server:
#   port: 8097
# MySql #
# spring.jpa.hibernate.ddl-auto=update
#spring:
#  jpa: 
#    hibernate: 
#      ddl-auto: update
#    show-sql: true
    
#  datasource: 
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_ms_clientes
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
  
#spring.jpa.show-sql: true

