server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

spring:
  cloud:
    discovery:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      departmentService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThresdhold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  ratelimiter:
    instances:
      departmentService:
        limitForPeriod: 2
        limitRefreshPeriod: 5s
        timeoutDuration: 10s
        registerHealthIndicator: true
        eventConsumerBufferSize: 100
  timelimiter:
    instances:
      departmentService:
        timeoutDuration: 2s
        cancelRunningFuture: true
  retry:
    instances:
      departmentService:
        maxRetryAttempts: 5
        waitDuration: 10s
  bulkhead:
    instances:
      departmentService:
        maxWaitDuration: 5s
        maxConcurrentCalls: 5
#  thread-pool-bulkhead:
#    instances:
#      departmentService:
#        maxThreadPoolSize: 1
#        coreThreadPoolSize: 1
#        queueCapacity: 1

