server:
   port: 8080
   
# MySql #
spring:
  jpa: 
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate: 
      ddl-auto: update
    show-sql: true
  datasource: 
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/db_security?createDatabaseIfNotExist=true&useSSL=true
    username: uncledave
    password: Test@123
    driver-class-name: com.mysql.cj.jdbc.Driver

# Server Admin Client
  boot:
    admin:
      client:
        url: http://localhost:8890
        instance:
          management-base-url: http://localhost:${server.port}
          
# Server Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
   instance:
      instance-id: ${spring.application.name}:${server.port}-${spring.application.instance_id:${random.value}}  
            
# Endpoints exposition
management:
  endpoints:
    web:
     exposure:
       include: "*"
     health:
       show-details: always