server:
  port: 8887

# Server Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         #defaultZone: http://host.docker.internal:8889/eureka
         defaultZone: http://localhost:8889/eureka
   instance:
      instance-id: ${spring.application.name}:${server.port}-${spring.application.instance_id:${random.value}}        
spring:
   # Server Admin Client
  boot:
    admin:
      client:
        url: http://localhost:8890
        instance:
          management-base-url: http://localhost:${server.port}
          
 # Mapeo de Microservicios
  cloud:
    gateway:
      discovery.locator:          
          enabled: true           
          lowerCaseServiceId: true
      httpclient:
        pool:
          max-connections: 200 # Ajusta según la carga esperada
        connect-timeout: 10000 # Tiempo de espera para establecer la conexión (milisegundos)
        response-timeout: 1200000 # Tiempo de espera para obtener una respuesta (milisegundos)

# Personalizado - Routers
      routes:
#      - id: ms-negocio-gestion-catalogo
#        uri: lb://ms-negocio-gestion-catalogo
#        predicates:
#          - Path=/api/tipo-plan/**
#          - Path=/api/parametro/**
#          - Path=/api/tipo-contribuyente/**
#          - Path=/api/tipo-proceso/**
#          - Path=/api/tributo/**
          
      - id: ms-negocio-gestion-inscripcion-vta
        uri: lb://ms-negocio-gestion-inscripcion-vta
        predicates:
          - Path=/api/inscripciones-vta/**

#      - id: ms-administracion-server-registry
#        uri: http://host.docker.internal:8761
#        predicates:
#          - Path=/eureka/**
#          
#      - id: ms-administracion-server-registry-static
#        uri: http://host.docker.internal:8761
#        predicates:
#          - Path=/eureka/** 
          
#      - id: ms-negocio-gestion-catalogo-actuator
#        uri: lb://MS-NEGOCIO-GESTION-CATALOGO/actuator
#        predicates:
#          - Path=/eureka/**  
#        filters:         
#        - RewritePath=/ms-instructor/(?<path>.*), /$\{path}        
#      - id: albums
#        uri: https://jsonplaceholder.typicode.com/albums
#        predicates:
#        - Path=/albums
        
# Endpoints exposition
# Acuator
management:
  endpoints:
    web:
      exposure:
        include: "health, prometheus"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true 
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
         