server:
  port: 8887

# Server Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
   instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} 
           
spring:
   # Server Admin Client
  boot:
    admin:
      client:
        url: http://localhost:8890
        instance:
          management-base-url: http://localhost:${server.port}
          
 # Mapeo de Microservicios
  cloud:
    gateway:
      routes:
      - id: id-ms-catalogo
        uri: lb://MS-NEGOCIO-GESTION-CATALOGO
        predicates:
        - Path=/api/v2/tipo-plan/**
#        filters:         
#        - RewritePath=/ms-clientes/(?<path>.*), /$\{path}        
      - id: albums
        uri: https://jsonplaceholder.typicode.com/albums
        predicates:
        - Path=/albums1/**
        
        
#        spring:
#  cloud:
#    gateway:
#      routes:
#      - id: path_route
#        uri: https://example.org
#        predicates:
#        - Path=/red/{segment},/blue/{segment}
        
        
# Endpoints exposition
# Acuator
management:
  endpoints:
    web:
      exposure:
        include: "health, prometheus"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true    