server:
   port: 8092
   
# MySql #
spring:
  jpa: 
    hibernate: 
      ddl-auto: create
    show-sql: true
  datasource: 
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3309/db_ms_cliente?createDatabaseIfNotExist=true&useSSL=true
    username: uncledave
    password: Test123
    driver-class-name: com.mysql.cj.jdbc.Driver

    
# Server Admin Client
  boot:
    admin:
      client:
        url: http://localhost:8890
        instance:
          management-base-url: http://localhost:${server.port}
          
# Server Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
         
# Endpoints exposition
management:
  endpoints:
    web:
     exposure:
       include: "*"
     health:
       show-details: always