server:
   port: 8290
   
# Mongo DB #
spring:
 data:
  mongodb:
   host: localhost
   port: 27017
   database: db_parametro_dev
   auto-index-creation: false
#   username: sa
#   password: sa
   
#spring:
# data:
#  mongodb:
#   host: localhost
#   port: 27017
#   database: tutorial
# autoconfigure:
#  exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    
   
     

# Server Admin Client
  boot:
    admin:
      client:
        url: http://localhost:8890
        instance:
          management-base-url: http://localhost:${server.port}
          
# Server Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
   instance:
      instance-id: ${spring.application.name}:${server.port}-${spring.application.instance_id:${random.value}}        
# Endpoints exposition
# Acuator
management:
  endpoints:
    web:
      exposure:
        include: "health, prometheus"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true 
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0