server:
   port: 8092
   
# Mongo DB #
spring:
 data:
  mongodb:
   host: localhost
   port: 27017
   database: tutorial
   auto-index-creation: false
   
#spring:
# data:
#  mongodb:
#   host: localhost
#   port: 27017
#   database: tutorial
# autoconfigure:
#  exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    
   
     

# Server Admin Client
  boot:
    admin:
      client:
        url: http://localhost:8890
        instance:
          management-base-url: http://localhost:${server.port}
          
# Server Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
         
# Endpoints exposition
management:
  endpoints:
    web:
     exposure:
       include: "*"
     health:
       show-details: always